open-cluster-management-io/cluster-proxy

README.md
cc @qiujian16 
Signed-off-by: yue9944882 <291271447@qq.com>
=> Clarify performance loss

charts/cluster-proxy/Chart.yaml, charts/cluster-proxy/templates/clusterrole.yaml, charts/cluster-proxy/templates/managedproxyconfiguration.yaml, charts/cluster-proxy/templates/manager-deployment.yaml, charts/cluster-proxy/values.yaml, pkg/addon/agent/agent.go, pkg/addon/operator/authentication/selfsigned/secret.go, pkg/common/constants.go
Signed-off-by: yue9944882 <291271447@qq.com>
=> Default agent installation by installStrategy

cmd/addon-manager/main.go
fix: Error log message not print when `--agent-image-name` not set.
=> Fix: log init

README.md
=> Doc: Clarifying README - minor updates

cmd/addon-manager/main.go, controllers/clustermanagementaddon_controller.go, controllers/ensure_secret_test.go, go.mod, pkg/addon/operator/authentication/selfsigned/self_sign_certificate.go
=> Bugfix: Entrypoint should be included in the SANs

cmd/addon-manager/main.go, controllers/clustermanagementaddon_controller.go, pkg/addon/agent/agent.go
Signed-off-by: champly <champly@outlook.com>
- some args not init.
- klog init fix.
- add proxy-agent `cluster-proxy-open-cluster-management.io-proxy-agent-signer-client-cert` secret.
=> Bugfix: some bug fix.

Makefile, charts/cluster-proxy/templates/manager-deployment.yaml, charts/cluster-proxy/values.yaml, cmd/Dockerfile, controllers/manifests.go, pkg/addon/agent/agent.go
=> Chore: Switch to quay.io image and merge the binaries

.github/workflows/go-postsubmit.yml
=> gh-action: post-submit push

.github/workflows/go-postsubmit.yml, cmd/Dockerfile
=> Fixes post-submit build-push job

README.md, cmd/Dockerfile
=> Chore: Fixes the post submit build

.github/workflows/go-release.yml
=> gh-action: Release job

.github/workflows/go-release.yml
>Signed-off-by: yue9944882 <291271447@qq.com>
=> Fixes release gh action

charts/cluster-proxy/Chart.yaml, charts/cluster-proxy/values.yaml
=> Cut v0.1.0 release for helm chart

pkg/apis/proxy/v1alpha1/doc.go
=> Bugfix: Remove import restriction

charts/cluster-proxy/crds/managedproxyconfigurations.yaml
=> Chore: Sync up chart crd

charts/cluster-proxy/Chart.yaml, charts/cluster-proxy/values.yaml
=> Bump charts to v0.1.1

cmd/addon-agent/main.go
=> Bugfix: Init klog flags

cmd/Dockerfile
=> Chore: Remove gocn proxy

cmd/Dockerfile
=> Chore: Compact docker image layer

cmd/Dockerfile
=> Chore: Grant kubectl x permission

cmd/Dockerfile
=> Fixes insufficient x permission

pkg/addon/agent/agent.go
Fixes: https://github.com/open-cluster-management-io/cluster-proxy/issues/44
/assign @xuezhaojun
=> Bugfix: Proxy-agent args proxy server namespace

charts/cluster-proxy/templates/managedproxyconfiguration.yaml
=> Remove field not in use

charts/cluster-proxy/crds/managedproxyconfigurations.yaml, charts/cluster-proxy/templates/managedproxyconfiguration.yaml, charts/cluster-proxy/values.yaml, hack/crd/bases/proxy.open-cluster-management.io_managedproxyconfigurations.yaml, pkg/apis/proxy/v1alpha1/managedproxyconfiguration_types.go, pkg/proxyagent/agent/agent.go, pkg/proxyagent/agent/manifests/charts/addon-agent/templates/addon-agent-deployment.yaml, pkg/proxyagent/agent/manifests/charts/addon-agent/values.yaml
related issue: https://github.com/open-cluster-management-io/cluster-proxy/issues/74
=> Add proxy-server-port in proxy-agent

pkg/proxyserver/controllers/clustermanagementaddon_controller.go, pkg/proxyserver/controllers/ensure_secret_test.go
=> Add hostname to sans

examples/test-client/main.go
Related PR: https://github.com/oam-dev/cluster-gateway/pull/61
=> Update test-client in example

pkg/proxyagent/agent/manifests/charts/addon-agent/templates/addon-agent-deployment.yaml
=> Revert "bugfix: fixes cluster-proxy addon agent image rendering (#82)"

pkg/config/agent.go, pkg/config/agent_test.go, pkg/proxyagent/agent/agent.go
=> Fix registry name with port

cmd/addon-manager/main.go, pkg/config/agent.go, pkg/config/agent_test.go, pkg/proxyagent/agent/agent.go
Using the image of `proxy-agent`  as the default image of `agent-proxy` .
=> Add default agent image name

pkg/proxyserver/controllers/clustermanagementaddon_controller_test.go
=> Fix: wait for mgr started, then run test cases

pkg/proxyserver/controllers/clustermanagementaddon_controller.go
=> Fix:Should return false status when secret not found

.github/workflows/go-presubmit.yml, Makefile, cmd/addon-agent/main.go, cmd/addon-manager/main.go, e2e/framework/scheme.go
=> add go lint

go.mod, go.sum
=> Upgrade: addon-framework

.github/workflows/go-postsubmit.yml, .github/workflows/go-presubmit.yml, .github/workflows/go-release.yml
=> Update: remove gopath env in github pre submit yaml

.github/workflows/go-presubmit.yml, charts/cluster-proxy/templates/managedproxyconfiguration.yaml, examples/access-exported-services/main.go, pkg/proxyagent/agent/agent.go, pkg/proxyagent/agent/agent_test.go, pkg/proxyagent/agent/manifests/charts/addon-agent/templates/services-to-expose.yaml, test/e2e/connect/connect.go, test/e2e/e2e_test.go
=> Fix agent template field and e2e test cases issue.

.github/workflows/go-postsubmit.yml, .github/workflows/go-presubmit.yml, .github/workflows/go-release.yml, cmd/Dockerfile, go.mod
=> Upgrade go versiont to 1.19.

OWNERS
=> Add a owner.

pkg/util/serviceresolver_test.go, pkg/util/serviceurl_test.go
=> Add: unit-test cases in util pkg.

pkg/proxyagent/agent/agent.go
=> Fix: shoud update agent generation in all entrypoint types.

pkg/proxyagent/agent/manifests/charts/addon-agent/templates/namespace.yaml
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
=> fix the addon ns orphan

go.mod, go.sum, pkg/proxyagent/agent/agent_test.go, test/e2e/install/install.go, test/integration/controllers/clustermanagementaddon_controller_test.go
=> Rearrange e2e test cases.

pkg/proxyagent/agent/agent.go
The related addon-framework code: https://github.com/open-cluster-management-io/addon-framework/blob/9de90ed830ad9f59c0554d0516c548d808fbb053/pkg/utils/permission.go#L265
=> Fix: too many update of rolebinding.

client/client.go, cmd/addon-manager/main.go, go.mod, go.sum, hack/crd/bases/cluster.open-cluster-management.io_managedclustersets.yaml, hack/crd/cluster/managedclusterset.yaml, pkg/proxyagent/agent/agent.go, pkg/proxyagent/agent/agent_test.go, pkg/proxyserver/controllers/service_resolver_controller.go, pkg/proxyserver/operator/eventhandler/clusterset_event.go, test/e2e/connect/connect.go, test/e2e/framework/scheme.go, test/integration/controllers/serviceresolver_controller_test.go, test/integration/controllers/suite_test.go
https://github.com/open-cluster-management-io/ocm/issues/67
=> Upgrade go.mod open-cluster-management.io api.

charts/cluster-proxy/templates/clustermanagementaddon.yaml, charts/cluster-proxy/templates/clustersetbinding.yaml, charts/cluster-proxy/templates/manager-deployment.yaml, charts/cluster-proxy/templates/placement.yaml, cmd/addon-manager/main.go
Remove `agent-install-all` flag and define `installStrategy` in ClusterManagementAddOn.
=> Define `installStrategy` in ClusterManagementAddOn

charts/cluster-proxy/Chart.yaml
Upgrade chart to pass github gorelease check.
=> Upgrade chart version to 0.6.0.
